version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=django_project_db
